<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Translatable\HasTranslations;

class PackageValues extends Model
{
    use HasTranslations;

    public $translatable = ['value'];

    protected $guarded = [];
    protected $table = 'package_values';
    public const manager_route = 'manager.package_value.';

    protected static function boot()
    {
        parent::boot(); //  Change the autogenerated stub
        static::addGlobalScope('orderedBy', function (Builder $builder) {
            $builder->latest('updated_at');
        });
    }

    public function package()
    {
        return $this->belongsTo(Package::class);
    }

    public function getActionButtonsAttribute()
    {
        $button = '';
        $button .= '<a href="' . route(self::manager_route . 'edit', $this->id) . '" class="btn btn-icon btn-danger "><i class="la la-pencil"></i></a> ';
        $button .= '<button type="button" data-id="' . $this->id . '" data-toggle="modal" data-target="#deleteModel" class="deleteRecord btn btn-icon btn-danger"><i class="la la-trash"></i></button>';
        return $button;
    }

}
