<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Translatable\HasTranslations;

class Service extends Model
{
    use HasTranslations;

    public $translatable = ['name', 'details'];

    protected $guarded = [];
    protected $table = 'services';

    public const f3Types = [
        'Help in choosing the accounting program' => 1,
        'Establishing the chart of accounts' => 2,
        'Training service' => 3,
    ];
    public const company_offers = [
        'Service' => 1,
        'Product' => 2,
    ];

//    protected static function boot()
//    {
//        parent::boot(); //  Change the autogenerated stub
//        static::addGlobalScope('orderedBy', function (Builder $builder) {
//            $builder->latest('updated_at');
//        });
//    }

    public function getImageAttribute($value)
    {
        return is_null($value) ? defaultUserImage() : asset($value);
    }


    public function getActionButtonsAttribute()
    {
        $button = '';
        $button .= '<a href="' . route('manager.service.edit', $this->id) . '" class="btn btn-icon btn-danger "><i class="la la-pencil"></i></a> ';
        $button .= '<button type="button" data-id="' . $this->id . '" data-toggle="modal" data-target="#deleteModel" class="deleteRecord btn btn-icon btn-danger"><i class="la la-trash"></i></button>';
        return $button;
    }
}
